language: node_js
node_js: lts/*

cache:
  directories:
    - node_modules

script:
  - npm install

notifications:
  email: false

deploy:
  provider: heroku
  edge: true # opt in to dpl v2
  app: glacial-chamber-22605
